[package]
name = "open_gl_take_2"
version = "0.1.0"
authors = ["Vicix"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.40.0"
gl = "0.10.0"
image = "0.19.0"